config/routes.rb
Rails.application.routes.draw do

  resources :templates do
    member do
      post :duplicate
      get :preview
    end
  end

  resources :campaigns do
    member do
      get :campaign_subject
      patch :campaign_subject
      get :choose_template
      patch :choose_template
      get :write_content
      patch :write_content
      get :schedule_email
      patch :schedule_email

      post :duplicate
      patch :update_send
      put :update_send
      get :preview
    end
  end
  resources :emaillists do
    member do
      get :add_contact
      put :set_default
      delete :remove_contact
    end
  end
  resources :contacts
  resources :users

  resources :from_emails

  class OnlyAjaxRequest
    def matches?(request)
      request.xhr?
    end
  end

  root 'pages#home'

  get 'pages/home'
  get 'dashboard', to: 'pages#dashboard'
  get 'signup' => 'users#new', :as => "signup"

  get 'login' => 'session#new', :as => "login"
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy', :as => "logout"

  get 'forgot_password', to: 'pages#forgot_password'

  # pages
  get 'features', to: 'pages#features'
  get 'pricing', to: 'pages#pricing'
  get 'security', to: 'pages#security'
  get 'guides', to: 'pages#guides'
  get 'faqs', to: 'pages#faqs'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'contact', to: 'pages#contact'
end

app/views/templates/_form.html.erb
<%= form_with(model: template, local: true) do |form| %>
  <% if template.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h6><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h6>

      <ul>
        <% template.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", required: "required" %>
  </div>
  <div class="form-group">
    <label class="text-capitalize" for="template_content">HTML Template</label>
    <%= form.text_area :content, class: "form-control", id: "template_content" %>
    <small class="shorttag-sm text-muted">use <strong>%%content%%</strong> short tag for the placement of the email content</small>
  </div>
  <% if is_admin? %>
  <div class="form-group">
    <%= form.check_box :visible, { checked: @template.visible }, 1, 0 %>
    <label class="form-check-label" for="defaultCheck1">
      Set Visible to Users
    </label>
  </div>
  <% end %>
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary pl-4 pr-4 mr-2"> Save </button> <%= link_to "Cancel", templates_url, :class => 'btn btn-light' %>
    </div>
    <% if locals[:method] == "edit" %>
      <div class="col-sm-2">
        <%= link_to "Remove", template_url(@template), :class => "btn btn-danger float-right", method: :delete, data: { confirm: 'Are you sure?' }, remote: true  %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<div class="mt-5 my-3 p-3 bg-white rounded shadow-sm">
  <h5 class="border-bottom border-gray pb-2 mb-0">Editing Template</h5>
  <div class="pt-3">
    <%= render 'form', template: @template, locals: {method: 'edit'} %>
  </div>
</div>

app/views/templates/index.html.erb
<div class="mt-5 my-1 p-3 bg-white rounded shadow-sm">
  <% if notice %>
    <div class="alert alert-secondary"><%= notice %></div>
  <% end %>
  <div class="d-flex justify-content-between border-bottom border-gray pb-2 mb-0">
    <h5>Templates</h5>
    <%= link_to 'Create New', new_template_url, class: 'btn btn-primary btn-sm' %>
  </div>
  <div class="pt-3">
    <table class="table table-sm table-borderless table-hover">
      <tbody>
      <% @templates.each do |template| %>
        <tr>
          <td><%= template.name %></td>
          <td style="width: 32px;">
            <%= link_to template_url(template), class: 'btn btn-info btn-sm', title: "Preview", remote: true, data: {name: template.name} do %>
              <i class="fa fa-eye" aria-hidden="true"></i>
            <% end %>
          </td>

          <% if is_admin? %>
            <td style="width: 32px;">
              <%= link_to edit_template_url(template), class: 'btn btn-warning btn-sm', title: "Edit" do %>
                <i class="fa fa-edit" aria-hidden="true"></i>
              <% end %>
            </td>
          <% else %>
            <% unless template.admin_default %>
              <td style="width: 32px;">
                <%= link_to edit_template_url(template), class: 'btn btn-warning btn-sm', title: "Edit" do %>
                  <i class="fa fa-edit" aria-hidden="true"></i>
                <% end %>
              </td>
            <% end %>
          <% end %>

          <td style="width: 32px;">
            <%= link_to duplicate_template_url(template), class: 'btn btn-secondary btn-sm', title: "Duplicate", method: :post do %>
              <i class="fa fa-copy" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>


<div class="modal fade" id="templateShowModal" data-backdrop="static" tabindex="-1" aria-labelledby="templateShowModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="templateShowModalLabel">Template preview for <span id="templateModalName"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="templateModalContent">
          <iframe id="templateModalFrame" src="" width="100%" frameBorder="0">
            //show template here
          </iframe>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/templates/new.html.erb
<div class="mt-5 my-3 p-3 bg-white rounded shadow-sm">
  <h5 class="border-bottom border-gray pb-2 mb-0">New Template</h5>
  <div class="pt-3">
    <%= render 'form', template: @template, locals: {method: 'new'} %>
  </div>
</div>

app/views/templates/preview.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width" initial-scale="1">
  <!--[if !mso]>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <![endif]-->
  <meta name="x-apple-disable-message-reformatting">
  <title></title>
  <!--[if mso]>
  <style>
    * { font-family: sans-serif !important; }
  </style>
  <![endif]-->
  <!--[if !mso]><!-->
  <!-- Insert font reference, e.g. <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700" rel="stylesheet"> -->
  <!--<![endif]-->
  <style>
    *,
    *:after,
    *:before {
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
    }
    * {
      -ms-text-size-adjust: 100%;
      -webkit-text-size-adjust: 100%;
    }
    html,
    body,
    .document {
      width: 100% !important;
      height: 100% !important;
      margin: 0;
      padding: 0;
    }
    body {
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      text-rendering: optimizeLegibility;
    }
    div[style*="margin: 16px 0"] {
      margin: 0 !important;
    }
    table,
    td {
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
    }
    table {
      border-spacing: 0;
      border-collapse: collapse;
      table-layout: fixed;
      margin: 0 auto;
    }
    img {
      -ms-interpolation-mode: bicubic;
      max-width: 100%;
      border: 0;
    }
    *[x-apple-data-detectors] {
      color: inherit !important;
      text-decoration: none !important;
    }
    .x-gmail-data-detectors,
    .x-gmail-data-detectors *,
    .aBn {
      border-bottom: 0 !important;
      cursor: default !important;
    }
    .btn {
      -webkit-transition: all 200ms ease;
      transition: all 200ms ease;
    }
    .btn:hover {
      background-color: dodgerblue;
    }
    @media screen and (max-width: 750px) {
      .container {
        width: 100%;
        margin: auto;
      }
      .stack {
        display: block;
        width: 100%;
        max-width: 100%;
      }
    }
  </style>
</head>
<body>
<div style="display: none; max-height: 0px; overflow: hidden;">&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;</div>
<table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" class="document">
  <tr>
    <td valign="top">
      <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" width="750" class="container">
        <tr>
          <td>
            <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" width="100%">
              <tr>
                <td>
                  <%= @template.content.html_safe %>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <table role="presentation" aria-hidden="true" cellspacing="0" cellpadding="0" border="0" align="center" width="750" class="container">
        <tr>
          <td>
            <!-- Physical address -->
          </td>
        </tr>
        <tr>
          <td>
            <!-- Unsubscribe link -->
            <unsubscribe></unsubscribe>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @template.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @template.content %>
</p>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>

app/views/templates/show.js.erb
$('#templateShowModal').find('#templateModalName').text("<%= @template.name %>");
$('#templateShowModal').find('#templateModalFrame').attr("src", "<%= preview_template_url(@template) %>");
$('#templateShowModal').modal('show');