config/routes.rb
Rails.application.routes.draw do

  resources :templates do
    member do
      post :duplicate
      get :preview
    end
  end

  resources :campaigns do
    member do
      get :campaign_subject
      patch :campaign_subject
      get :choose_template
      patch :choose_template
      get :write_content
      patch :write_content
      get :schedule_email
      patch :schedule_email

      post :duplicate
      patch :update_send
      put :update_send
      get :preview
    end
  end
  resources :emaillists do
    member do
      get :add_contact
      put :set_default
      delete :remove_contact
    end
  end
  resources :contacts
  resources :users

  resources :from_emails

  class OnlyAjaxRequest
    def matches?(request)
      request.xhr?
    end
  end

  root 'pages#home'

  get 'pages/home'
  get 'dashboard', to: 'pages#dashboard'
  get 'signup' => 'users#new', :as => "signup"

  get 'login' => 'session#new', :as => "login"
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy', :as => "logout"

  get 'forgot_password', to: 'pages#forgot_password'

  # pages
  get 'features', to: 'pages#features'
  get 'pricing', to: 'pages#pricing'
  get 'security', to: 'pages#security'
  get 'guides', to: 'pages#guides'
  get 'faqs', to: 'pages#faqs'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'contact', to: 'pages#contact'
end

app/models/emaillist.rb
class Emaillist < ApplicationRecord
  belongs_to :user
  has_many :contacts

  before_destroy :prevent_remove_default

  def self.count
    self.contacts.count
  end

  def toggle_default
    self.user.emaillists.where.not(id: self.id).where(default: true).update_all(default: false)
    self.update_attribute(:default, true)
  end

  protected
  def prevent_remove_default
    return unless default
    errors.add(:base, "Cannot remove default email list")
    throw :abort
  end
end

app/controllers/emaillists_controller.rb
class EmaillistsController < ApplicationController
  before_action :set_emaillist, only: [:show, :edit, :update, :destroy, :add_contact, :set_default, :remove_contact]
  before_action :require_login

  # GET /emaillists
  # GET /emaillists.json
  def index
    @emaillists = current_user.emaillists
  end

  # GET /emaillists/1
  # GET /emaillists/1.json
  def show
    @contacts = @emaillist.contacts.where(archived: false)
  end

  # GET /emaillists/new
  def new
    @emaillist = current_user.emaillists.new
  end

  # GET /emaillists/1/edit
  def edit
  end

  # POST /emaillists
  # POST /emaillists.json
  def create
    @emaillist = current_user.emaillists.new(emaillist_params)

    respond_to do |format|
      if @emaillist.save
        format.js { redirect_to emaillists_url }
        format.html { redirect_to @emaillist, notice: 'Email List was successfully created.' }
        format.json { render :show, status: :created, location: @emaillist }
      else
        format.js {}
        format.html { render :new }
        format.json { render json: @emaillist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emaillists/1
  # PATCH/PUT /emaillists/1.json
  def update
    respond_to do |format|
      if @emaillist.update(emaillist_params)
        format.html { redirect_to @emaillist, notice: 'Email List was successfully updated.' }
        format.json { render :show, status: :ok, location: @emaillist }
      else
        format.html { render :edit }
        format.json { render json: @emaillist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emaillists/1
  # DELETE /emaillists/1.json
  def destroy
    @emaillist.destroy
    respond_to do |format|
      if @emaillist.default
        @contacts = @emaillist.contacts.where(archived: false)
        format.html { render :show }
      else
        format.html { redirect_to emaillists_url }
      end
      format.json { render json: @emaillist.errors, status: :unprocessable_entity }
    end
  end

  def add_contact
    respond_to do |format|
      format.js {}
    end
  end

  def set_default
    @emaillist.toggle_default

    respond_to do |format|
      format.js { redirect_to @emaillist, notice: "Email list was set to default" }
    end
  end

  def remove_contact
    @contact = nil
    if params[:contact_id].present?
      @contact = @emaillist.contacts.find(params[:contact_id])
      @contact.remove_from_list()
    end
    respond_to do |format|
      format.js { redirect_to @emaillist, notice: "Contact removed from list" }
      # format.js { }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_emaillist
    @emaillist = current_user.emaillists.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def emaillist_params
    params.require(:emaillist)
        .permit(:name)
  end
end

app/helpers/emaillists_helper.rb
module EmaillistsHelper
end

app/views/emaillists/add_contact.js.erb
//Todo
alert('Todo');

app/views/emaillists/create.js.erb
alert('success');

app/views/emaillists/edit.js.erb
$('#emailListModal').modal('show');

app/views/emaillists/index.html.erb
<div class="mt-5 my-1 p-3 bg-white rounded shadow-sm">
  <% if notice %>
    <div class="alert alert-secondary"><%= notice %></div>
  <% end %>
  <div class="d-flex justify-content-between border-bottom border-gray pb-2 mb-0">
    <h5>Email Lists</h5>
    <%= link_to 'Create New', new_emaillist_url, class: 'btn btn-primary btn-sm', remote: true %>
  </div>
  <div class="pt-3">
    <div class="list-group">

      <% @emaillists.each do |list| %>
        <a href="<%= emaillist_url(list) %>" class="list-group-item list-group-item-action  d-flex align-items-center">
          <spa class="flex-grow-1"><%= list.name %></spa>
          <% if list.default %>
            <span class="badge badge-success badge-pill mr-1">default</span>
          <% end %>
          <span class="badge badge-secondary badge-pill"><%= list.contacts.where(archived: false).count %></span>
        </a>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="newEmailListModal" tabindex="-1" aria-labelledby="newEmailListModalLabel" data-backdrop="static" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <%= form_with model: Emaillist.new, url: emaillists_url, class: 'nobottommargin login-form', data: {remote: true} do |f| %>
      <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New Email List</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div class="form-group">
              <%= f.label :name, class: 'text-capitalize' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/emaillists/new.js.erb
$('#newEmailListModal').modal('show');

app/views/emaillists/remove_contact.js.erb
console.log('<%= @emaillist.id %>');

app/views/emaillists/show.html.erb
<div class="mt-5 my-1 p-3 bg-white rounded shadow-sm">
  <% if notice %>
    <div class="alert alert-secondary"><%= notice %></div>
  <% end %>
  <% if @emaillist.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <% @emaillist.errors.full_messages.each do |message| %>
        <p class="mb-0"><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <div class="d-flex justify-content-between border-bottom border-gray pb-2 mb-0">
    <h5><%= @emaillist.name %></h5>
    <div class="dropdown right_menu">
      <button class="btn btn-light dropdown-toggle btn-sm" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu2">
        <%= link_to edit_emaillist_url(@emaillist), class: "dropdown-item", remote: true do %>
          Edit name
        <% end %>
        <% unless @emaillist.default %>
          <%= link_to set_default_emaillist_url, class: "dropdown-item", method: :put, remote: true do %>
            Set as default
          <% end %>
        <% end %>
        <%= link_to add_contact_emaillist_url, class: "dropdown-item", remote: true do %>
          Add contact to list
        <% end %>
        <% unless @emaillist.default %>
          <%= link_to @emaillist, class: "dropdown-item", method: :delete, data: {confirm: "Are you sure?"} do %>
            Delete List
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
  <div class="pt-3">
    <table class="table table-sm">
      <tr>
        <th>Email</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th colspan="2">Actions</th>
      </tr>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.email %></td>
          <td><%= contact.first_name %></td>
          <td><%= contact.last_name %></td>
          <td style="width: 32px;">
            <%= link_to contact, class: 'btn btn-info btn-sm', title: "View contact", remote: true do %>
              <i class="fa fa-eye" aria-hidden="true"></i>
            <% end %>
          </td>
          <td style="width: 32px;">
            <%= link_to remove_contact_emaillist_url(@emaillist, contact_id: contact.id), method: :delete, class: 'btn btn-danger btn-sm', title: "Remove contact from list", remote: true do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>

  </div>
</div>

<div class="modal fade" id="emailListModal" tabindex="-1" aria-labelledby="emailListModalLabel" data-backdrop="static" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <%= form_with model: @emaillist, url: emaillist_url(@emaillist), class: 'nobottommargin login-form', method: :put, data: {remote: true} do |f| %>
        <div class="modal-header">
          <h5 class="modal-title" id="emailListModalLabel">Email List</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name, class: 'text-capitalize' %>
            <%= f.text_field :name, value: @emaillist.name, class: 'form-control' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      <% end %>
    </div>
  </div>
</div>