config/routes.rb
Rails.application.routes.draw do

  resources :templates do
    member do
      post :duplicate
      get :preview
    end
  end

  resources :campaigns do
    member do
      get :campaign_subject
      patch :campaign_subject
      get :choose_template
      patch :choose_template
      get :write_content
      patch :write_content
      get :schedule_email
      patch :schedule_email

      post :duplicate
      patch :update_send
      put :update_send
      get :preview
    end
  end
  resources :emaillists do
    member do
      get :add_contact
      put :set_default
      delete :remove_contact
    end
  end
  resources :contacts
  resources :users

  resources :from_emails

  class OnlyAjaxRequest
    def matches?(request)
      request.xhr?
    end
  end

  root 'pages#home'

  get 'pages/home'
  get 'dashboard', to: 'pages#dashboard'
  get 'signup' => 'users#new', :as => "signup"

  get 'login' => 'session#new', :as => "login"
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy', :as => "logout"

  get 'forgot_password', to: 'pages#forgot_password'

  # pages
  get 'features', to: 'pages#features'
  get 'pricing', to: 'pages#pricing'
  get 'security', to: 'pages#security'
  get 'guides', to: 'pages#guides'
  get 'faqs', to: 'pages#faqs'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'contact', to: 'pages#contact'
end

app/models/campaign.rb
=begin
  Campaign Status
  1. incomplete
  2. pending
  3. sent
=end
class Campaign < ApplicationRecord
  belongs_to :emaillist, optional: true
  belongs_to :template, optional: true
  belongs_to :user
  has_many :emailsends
  belongs_to :from_email, optional: true

  before_validation :set_datetime, on: [:create, :update]
  # after_commit :send_campaign_job, on: :create
  after_create :send_campaign_job
  before_create :set_from_email
  before_update :set_from_email

  def set_datetime
    # self.datetime_send = DateTime.strptime(self.datetime_send, "%m-%d-%Y %I:%M %p")
  end

  def from
    from_name ? from_name : from_email
  end

  def duplicate
    cmp = self.dup
    cmp.subject = self.subject + "(1)"
    cmp.status = 'incomplete'
    cmp.datetime_send = nil
    cmp.instant = nil
    cmp.status = "incomplete"

    cmp
  end

  def datetime_send_str
    begin
      dt = DateTime.parse(datetime_send.to_s)
      dt.strftime("%d/%m/%Y %I:%M %p")
    rescue => e
      nil
    end
  end

  def send_now
    from = "#{self.from_name} <#{self.from_email}>"
    subject = self.subject
    body = self.content
    emaillist.contacts.each do |contact|
      to = contact.email
      print(to)
      mail = CampaignMailer.with(to: to, from: from, subject: subject, body: body).send_campaign_email().deliver_now
    end
  end

  def self.test_send(who)
    #to = "marjone@owlreply.com"
    to = "kopf1988@gmail.com"
    to = who
    from = "Marjone <marjonedev@gmail.com>"
    subject = "Test Send from Owlcampaign"
    body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis sem turpis, non placerat diam suscipit eu. Suspendisse metus purus, gravida eu mi vel, eleifend euismod nunc."
    CampaignMailer.with(to: to, from: from, subject: subject, body: body).send_campaign_email.deliver_now
  end

  def send_campaign_job
    # CampaignSchedulerJob.set(wait: self.datetime_send).perform_later(self)
  end

  def content_full
    content = self.content ? self.content.to_s : ''
    if self.template
      self.template.content.to_s.gsub("%%content%%", content)
    else
      ''
    end
    # self.template.content
  end

=begin
  1.1. Email Subject
  1.2. From
    2.1. Template
    3.1 Content
      4.1 Email List
      4.2 Date
=end
  def get_step
    unless self.subject
      return "step1"
    end
    unless self.from_name
      return "step1"
    end
    unless self.from_email_id
      return "step1"
    end
    unless self.template
      return "step2"
    end
    unless self.content
      return "step3"
    end
    unless self.emaillist_id
      return "step4"
    end
    unless self.datetime_send
      return "step4"
    end

    "complete"
  end

  private
  def set_from_email
    self.from_email_address = FromEmail.find(self.from_email_id).email_address
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_action :set_campaign, only: [:show, :edit, :update, :destroy, :campaign_subject, :choose_template, :write_content, :schedule_email]
  before_action :require_login

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = current_user.campaigns.order("id DESC")
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = current_user.campaigns.new
    @subject = params[:subject]
  end

  # GET /campaigns/1/edit
  def edit

    @step = @campaign.get_step
    if @step == "step2"
      redirect_to action: :choose_template, controller: :campaigns, id: @campaign.id
    elsif @step == "step3"
      redirect_to action: :write_content, controller: :campaigns, id: @campaign.id
    elsif @step == "step4"
      redirect_to action: :schedule_email, controller: :campaigns, id: @campaign.id
    end

    @templates = Template.where(admin_default: true, visible: true).or(current_user.templates.all).order(admin_default: :desc)

  end

  # POST /campaigns
  # POST /campaigns.json
  def create
   @campaign = current_user.campaigns.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to action: :choose_template, controller: :campaigns, id: @campaign.id }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def campaign_subject
    if request.patch?
      respond_to do |format|
        if @campaign.update(campaign_params)
          format.html { redirect_to choose_template_campaign_url(@campaign) }
          format.json { render :show, status: :ok, location: @campaign }
        end
      end
    else

    end
  end

  def choose_template
    if request.patch?
      respond_to do |format|
        if @campaign.update(campaign_params)
          format.html { redirect_to action: :write_content, controller: :campaigns, id: @campaign.id }
          format.json { render :show, status: :ok, location: @campaign }
        else
          format.html { render :edit }
          format.json { render json: @campaign.errors, status: :unprocessable_entity }
        end
      end
    else
      @templates = Template.where(admin_default: true, visible: true).or(current_user.templates.all).order(admin_default: :desc)
      # Show the page to let them choose the template.
    end
  end

  def write_content
    if request.patch?
      respond_to do |format|
        if @campaign.update(campaign_params)
          format.html { redirect_to action: :schedule_email, controller: :campaigns, id: @campaign.id }
          format.json { render :show, status: :ok, location: @campaign }
        else
          format.html { render :edit }
          format.json { render json: @campaign.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def schedule_email
    if request.patch?
      respond_to do |format|
        if @campaign.update(campaign_params)
          #todo: check first if all completed
          @campaign.update_attribute(:status, 'pending')
          format.html { redirect_to :campaigns, notice: 'Success. Campaign was successfully scheduled.' }
          format.json { render :show, status: :ok, location: @campaign }
        else
          format.html { render :edit }
          format.json { render json: @campaign.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to campaigns_url, notice: 'Campaign was successfully updated.' }
        # format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' + campaign_params["datetime_send"] }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_send
    response_to do |format|
      if @campaign.update(campaign_params)
        @campaign.send
        format.html { redirect_to campaigns_url, notice: 'Campaign was successfully updated and added to queue for sending.' }
        format.json { render :show, status: :ok, location: campaigns_url }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def duplicate
    @campaign = Campaign.find(params[:id])
    @campaign = @campaign.duplicate

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to edit_campaign_url(@campaign), notice: 'Campaign was successfully copied.' }
        format.json { render :edit, status: :created, location: @campaign }
      else
        format.html { redirect_to campaigns_url, alert: "Error copying the campaign" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def preview
    @campaign = current_user.campaigns.find(params[:id])
    render :layout => false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_params
      params.require(:campaign).permit(:emaillist_id, :template_id, :name, :from_name, :from_email_id, :subject, :content, :datetime_send)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_edit_form.html.erb
<%= form_with(model: campaign, local: true) do |form| %>

  <% if campaign.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h6><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h6>

      <ul>
        <% campaign.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :subject, 'Email subject' %>
    <%= form.text_field :subject, class: "form-control", required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label :from, 'From name' %>
    <%= form.text_field :from_name, class: "form-control", required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label :from_email_id, 'From email address', class: 'form-label' %>
    <select name="campaign[from_email_id]" id="from_email_id" class="select2 form-control" required="required">
      <% current_user.from_emails.where(confirmed: true).each do |from| %>
        <option data-name="<%= from.name %>" value="<%= from.id %>" <% campaign.from_email_id == from.id ? "selected" : "" %>>
          <%= from.email_address %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <%= form.label :emaillist_id, "Email list" %>
    <select name="campaign[emaillist_id]" id="emaillist_ids" class="select2 form-control" required="required">
      <% current_user.emaillists.each do |list| %>
        <option value="<%= list.id %>" <% campaign.emaillist_id == list.id ? "selected" : "" %>>
          <%= list.name %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <%= form.label :template_id, "Template" %>
    <select name="campaign[template_id]" id="template_ids" class="select2 form-control" required="required">
      <% @templates.each do |template| %>
        <option value="<%= template.id %>" <% campaign.template_id == template.id ? "selected" : "" %>>
          <%= template.name %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <%= form.label :datetime_send, "When to send" %>
    <%= form.text_field :datetime_send, class: "form-control", data: {behavior: "flatpickr"} %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'btn btn-secondary px-4' %>
     <%= link_to "Cancel", campaigns_url, class: 'btn btn-light float-right'%>
  </div>
<% end %>

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, local: true) do |form| %>

  <% if campaign.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h6><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h6>

      <ul>
        <% campaign.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, 'Name your campaign' %>
    <%= form.text_field :name, class: "form-control", required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label :subject, 'Email subject' %>
    <%= form.text_field :subject, class: "form-control", required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label :from, 'From name' %>
    <%= form.text_field :from_name, class: "form-control", required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label :from, 'From email address' %>
    <%= form.text_field :from_email, class: "form-control", required: "required" %>
  </div>

  <div class="form-group">
    <%= form.label :emaillist_id, "Email list" %>
    <select name="campaign[emaillist_id]" id="emaillist_ids" class="select2 form-control" required="required">
      <% current_user.emaillists.each do |list| %>
        <option value="<%= list.id %>">
          <%= list.name %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <%= form.label :template_id, "Template" %>
    <select name="campaign[template_id]" id="template_ids" class="select2 form-control" required="required">
      <% @templates.each do |template| %>
        <option value="<%= template.id %>">
          <%= template.name %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <%= form.label :datetime_send, "When to send" %>
    <%= form.text_field :datetime_send, class: "form-control", data: {behavior: "flatpickr"} %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'btn btn-secondary pl-3 pr-3' %>
    <%= link_to "Cancel", campaigns_url, class: 'btn btn-light float-right'%>
  </div>
<% end %>

app/views/campaigns/campaign_subject.html.erb
<div class="mt-5 my-3 p-3 bg-white rounded shadow-sm">
  <h5 class="border-bottom border-gray pb-2 mb-0">Email Subject and From</h5>
  <div class="pt-3">
    <% campaign = @campaign %>

    <%= form_with(model: campaign, url: campaign_subject_campaign_url(@campaign), class: 'row g-3') do |form| %>

      <% if campaign.errors.any? %>
        <div id="error_explanation" class="alert alert-danger" role="alert">
          <h6><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h6>

          <ul>
            <% campaign.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group col-12">
        <%= form.label :subject, 'Email subject', class: 'form-label' %>
        <%= form.text_field :subject, class: "form-control", required: "required" %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :from_name, 'From name', class: 'form-label' %>
        <%= form.text_field :from_name, id: "from_name", class: "form-control", required: "required" %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :from_email_id, 'From email address', class: 'form-label' %>
        <select name="campaign[from_email_id]" id="from_email_id" class="select2 form-control" required="required">
          <% current_user.from_emails.where(confirmed: true).each do |from| %>
            <option data-name="<%= from.name %>" value="<%= from.id %>" <% campaign.from_email_id == from.id ? "selected" : "" %>>
              <%= from.email_address %>
            </option>
          <% end %>
        </select>
        <%#= form.text_field :from_email_id, class: "form-control disabled", required: "required" %>
        <%# TO DO: Allow users to have multiple 'from' email addresses, but the user has to validate they own the address first. %>
      </div>

      <div class="col-12 border-top border-gray pt-2">
        <%= form.submit "Continue to Next Step", class: 'btn btn-primary pl-3 pr-3' %>
        <%= link_to "Cancel", campaigns_url, class: 'btn btn-light float-right'%>
      </div>
    <% end %>

  </div>
</div>

<script type="text/javascript">
    $('#from_email_id').on('select2:select', function (e) {
        var data = e.params.data;
        let name = $(data.element).data("name");
        console.log(data)
        $('#from_name').val(name);
    });
</script>

app/views/campaigns/choose_template.html.erb
<div class="mt-5 my-3 p-3 bg-white rounded shadow-sm">
  <h5 class="border-bottom border-gray pb-2 mb-0">Pick A Template For Your Email</h5>
  <div class="row pt-3">
    <div class="col-auto mb-3">
      <%= link_to write_content_campaign_url(@campaign) do %>
      <div class="card h-100" style="width: 18rem;">
        <div class="card-body text-center">
          <i class="fa fa-plus fa-3x text-muted" aria-hidden="true"></i>
          <h4 class="text-muted">Create Custom</h4>
        </div>
      </div>
      <% end %>
    </div>
    <% if @templates.size > 0 %>
      <% for template in @templates %>
        <div class="col-auto mb-3">
          <div class="card  h-100" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= template.name %></h5>
  <!--            Todo: This will be the preview image part.-->
            </div>
            <div class="card-footer bg-transparent">
              <%= form_with model: @campaign, url: choose_template_campaign_url(@campaign) do |form| %>
                <%= form.hidden_field :template_id, value: template.id %>
                <%= form.submit "Choose", class: 'btn btn-primary btn-sm float-left' %>
              <% end %>
               <%= link_to template_url(template), class: 'btn btn-info btn-sm float-right', title: "Preview", remote: true, data: {name: template.name} do %>
                Preview
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <%# else %>
<!--      <div class="col-md-12 pb-3">-->
<!--        You have no template at the moment. <a href="<%#= templates_url %>" class="btn btn-dark btn-sm">Create new template now!</a>-->
<!--      </div>-->
    <% end %>
  </div>
  <div class="row">
    <div class="col-12 border-top border-gray pt-2">
      <%= link_to "Back", campaign_subject_campaign_url(@campaign), class: 'btn btn-secondary pl-3 pr-3' %>
      <%= link_to "Cancel", campaigns_url, class: 'btn btn-light float-right'%>
    </div>
  </div>
</div>


<div class="modal fade" id="templateShowModal" data-backdrop="static" tabindex="-1" aria-labelledby="templateShowModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="templateShowModalLabel">Template preview for <span id="templateModalName"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="templateModalContent">
          <iframe id="templateModalFrame" src="" width="100%" frameBorder="0">
            //show template here
          </iframe>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/edit.html.erb
<div class="mt-5 my-3 p-3 bg-white rounded shadow-sm">
  <h5 class="border-bottom border-gray pb-2 mb-0">Edit Campaign</h5>
  <div class="pt-3">
    <%= render 'edit_form', campaign: @campaign, locals: {method: 'edit'} %>
  </div>
</div>

app/views/campaigns/index.html.erb
<div class="mt-5 my-1 p-3 bg-white rounded shadow-sm">
  <% if notice %>
    <div class="alert alert-secondary"><%= notice %></div>
  <% end %>
  <div class="d-flex justify-content-between border-bottom border-gray pb-2 mb-0">
    <h5>Campaigns</h5>
    <%= link_to 'Create New', new_campaign_url, class: 'btn btn-primary btn-sm' %>
  </div>
  <div class="pt-3">
    <table class="table table-sm table-hover">
      <thead>
      <tr>
        <th>Subject</th>
        <th>Recipients</th>
        <th>Date & Time</th>
        <th>Status</th>
        <th colspan="2">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% if @campaigns.empty? %>
        <tr>
          <td class="text-center" colspan="5">No campaign available at the moment.</td>
        </tr>
      <% else %>
        <% @campaigns.each do |campaign| %>
          <tr data-href="<%= campaign_url(campaign) %>">
            <td><%= campaign.subject %></td>
            <td><%= campaign.emaillist&.name %></td>
            <td><%= campaign.datetime_send_str %></td>
            <td><%= campaign.status.capitalize %></td>
            <td style="width: 32px;">
              <%= link_to edit_campaign_url(campaign), class: 'btn btn-warning btn-sm', title: "Edit Campaign" do %>
                <i class="fa fa-edit" aria-hidden="true"></i>
              <% end %>
            </td>
            <td style="width: 32px;">
              <%= link_to duplicate_campaign_url(campaign), class: 'btn btn-secondary btn-sm', title: "Duplicate", method: :post do %>
                <i class="fa fa-copy" aria-hidden="true"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>



<script type="text/javascript">
  $(function(){
      $('*[data-href]').on('click', function (e) {
          const tgt = $(e.target);
          if(tgt.is("td")){
              e.preventDefault();
              window.location = $(this).data('href');
          }
      });
  });
</script>

app/views/campaigns/new.html.erb
<div class="mt-5 my-3 p-3 bg-white rounded shadow-sm">
  <h5 class="border-bottom border-gray pb-2 mb-0">New Campaign</h5>
  <div class="pt-3">
    <%#= render 'form', campaign: @campaign, locals: {method: 'new'} %>
    <% campaign = @campaign %>

    <%= form_with(model: campaign, local: true, class: 'row g-3') do |form| %>

      <% if campaign.errors.any? %>
        <div id="error_explanation" class="alert alert-danger" role="alert">
          <h6><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h6>

          <ul>
            <% campaign.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group col-12">
        <%= form.label :subject, 'Subject', class: 'form-label' %>
        <% subject = @subject ? @subject : '' %>
        <%= form.text_field :subject, class: "form-control", required: "required", value: subject %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :from_name, 'Who is it from?', class: 'form-label' %>
        <%= form.text_field :from_name, id: "from_name", class: "form-control", placeholder: "Name", required: "required", value: current_user.from_emails.where(default: true).first.name %>
      </div>

      <div class="form-group col-md-6">
        <label class="form-label">&nbsp;</label>
        <select name="campaign[from_email_id]" id="from_email_id" class="select2 form-control" required="required">
          <% current_user.from_emails.where(confirmed: true).each do |from| %>
            <option data-name="<%= from.name %>" value="<%= from.id %>">
              <%= from.email_address %>
            </option>
          <% end %>
        </select>
        <%#= form.label :from, 'From email address', class: 'form-label' %>
        <%#= form.text_field :from_email, class: "form-control disabled", required: "required", value: current_user.email_address, readonly: true %>
        <%# TO DO: Allow users to have multiple 'from' email addresses, but the user has to validate they own the address first. %>
      </div>

      <div class="col-12 border-top border-gray pt-2">
        <%= form.submit "Continue to Next Step", class: 'btn btn-primary pl-3 pr-3' %>
        <%= link_to "Cancel", campaigns_url, class: 'btn btn-light float-right'%>
      </div>
    <% end %>


  </div>
</div>

<script type="text/javascript">
    $('#from_email_id').on('select2:select', function (e) {
        var data = e.params.data;
        let name = $(data.element).data("name");
        $('#from_name').val(name);
    });
</script>

app/views/campaigns/schedule_email.html.erb
<div class="mt-5 my-3 p-3 bg-white rounded shadow-sm">
  <h4 class="pb-2 mb-2"><%= @campaign.subject %></h4>
  <h5 class="border-bottom border-gray ">Schedule Your Email</h5>
  <div class="pt-3">
    <% campaign = @campaign %>

    <%= form_with model: @campaign, url: schedule_email_campaign_url(@campaign) do |form| %>

      <div class="form-group">
        <%= form.label :emaillist_id, "Email list" %>
        <select name="campaign[emaillist_id]" id="emaillist_ids" class="select2 form-control" required="required">
          <% current_user.emaillists.each do |list| %>
            <option value="<%= list.id %>">
              <%= list.name %>
            </option>
          <% end %>
        </select>
      </div>

      <div class="form-group">
        <%= form.label :datetime_send, "When to send" %>
        <%= form.text_field :datetime_send, class: "form-control required", data: {behavior: "flatpickr"}, required: "required" %>
      </div>

      <div class="actions border-top border-gray pt-2">
        <%= link_to "Back", write_content_campaign_url(@campaign), class: 'btn btn-secondary pl-3 pr-3' %>
        <%= form.submit "Save and Schedule Email", class: 'btn btn-primary pl-3 pr-3' %>
        <%= link_to "Cancel", campaigns_url, class: 'btn btn-light float-right'%>
      </div>
    <% end %>


  </div>
</div>

app/views/campaigns/show.html.erb
<% if notice %>
  <div class="alert alert-secondary"><%= notice %></div>
<% end %>
<div class="p-3 bg-white rounded shadow-sm">
  <h4 class="mb-0">
    <%=@campaign.subject%>
    <%= link_to edit_campaign_url(@campaign), class: 'btn btn-light btn-sm float-right', title: "Edit Campaign" do %>
      <i class="fa fa-edit" aria-hidden="true"></i> Edit
    <% end %>
  </h4>
</div>
<div class="row">
  <div class="my-3 col-sm-12 col-md-4">
    <div class="p-3 bg-white rounded shadow-sm">
      <p>
        <strong>From:</strong><br />
        <%= @campaign.from_name ? "#{@campaign.from_name} <#{@campaign.from_email.email_address}>" : @campaign.from_email %>
      </p>
      <p>
        <strong>Send to list:</strong><br />
        <%= @campaign.emaillist&.name %>
      </p>

      <p>
        <strong>Template:</strong><br />
        <%= @campaign.template&.name %>
      </p>
      <p>
        <strong>Date & time to send:</strong><br />
        <%= @campaign.datetime_send_str %>
      </p>
    </div>
  </div>
  <div class="my-3 col-sm-12 col-md-8">
    <div class="p-3 bg-white rounded shadow-sm">
      <iframe id="templateModalFrame" src="<%= preview_campaign_url(@campaign) %>" width="100%" frameBorder="0">
        //show template here
      </iframe>
    </div>
  </div>
</div>

app/views/campaigns/write_content.html.erb
<div class="mt-5 my-3 p-3 bg-white rounded shadow-sm">
  <h5 class="border-bottom border-gray ">Write your new email content.</h5>
  <h4 class="pb-2 mb-0"><%= @campaign.subject %></h4>
  <div class="pt-3">
    <% campaign = @campaign %>


    <%= form_with model: @campaign, url: write_content_campaign_url(@campaign) do |form| %>

      <div class="form-group">
        <%= form.label :content %>
        <%= form.text_area :content, class: "form-control", rows: 20, required: "required" %>
      </div>

      <div class="actions border-top border-gray pt-2">
        <%= link_to "Back", choose_template_campaign_url(@campaign), class: 'btn btn-secondary pl-3 pr-3' %>
        <%= form.submit "Continue to Next Step", class: 'btn btn-primary pl-3 pr-3' %>
        <%= link_to "Cancel", campaigns_url, class: 'btn btn-light float-right'%>
      </div>
    <% end %>


  </div>

  <div id="gjs">
    <h1>Hello World Component!</h1>
  </div>
</div>


<%= javascript_pack_tag 'grapesjs' %>