config/routes.rb
Rails.application.routes.draw do

  resources :templates do
    member do
      post :duplicate
      get :preview
    end
  end

  resources :campaigns do
    member do
      get :campaign_subject
      patch :campaign_subject
      get :choose_template
      patch :choose_template
      get :write_content
      patch :write_content
      get :schedule_email
      patch :schedule_email

      post :duplicate
      patch :update_send
      put :update_send
      get :preview
    end
  end
  resources :emaillists do
    member do
      get :add_contact
      put :set_default
      delete :remove_contact
    end
  end
  resources :contacts
  resources :users

  resources :from_emails

  class OnlyAjaxRequest
    def matches?(request)
      request.xhr?
    end
  end

  root 'pages#home'

  get 'pages/home'
  get 'dashboard', to: 'pages#dashboard'
  get 'signup' => 'users#new', :as => "signup"

  get 'login' => 'session#new', :as => "login"
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy', :as => "logout"

  get 'forgot_password', to: 'pages#forgot_password'

  # pages
  get 'features', to: 'pages#features'
  get 'pricing', to: 'pages#pricing'
  get 'security', to: 'pages#security'
  get 'guides', to: 'pages#guides'
  get 'faqs', to: 'pages#faqs'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'contact', to: 'pages#contact'
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title><%= @page_title || 'Owl Campaign' %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= yield :javascript_includes %>
</head>

<body class="bg-light">
  <div class="d-flex flex-column flex-md-row align-items-center px-md-4 p-3 mb-3 nav-scroller bg-white shadow-sm box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="/" class="text-dark">OwlCampaign</a></h5>
    <ul class="nav my-2 my-md-0 mr-md-3">
      <% if logged_in? %>
        <li class="nav-item">
          <a class="<%= 'current' if current_page?(action: 'dashboard', controller: 'pages') %> nav-link p-2 text-dark" href="/dashboard">Dashboard</a>
        </li>
        <li class="<%= 'current' if current_page?(action: 'index', controller: 'campaigns') %> nav-item"><a class="nav-link p-2 text-dark" href="<%= campaigns_url %>">Campaigns</a></li>
        <li class="<%= 'current' if current_page?(action: 'index', controller: 'templates') %> nav-item"><a class="nav-link p-2 text-dark" href="<%= templates_url %>">Templates</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle p-2 text-dark" href="#" id="subscribersNavLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Subscribers</a>
          <div class="dropdown-menu" aria-labelledby="subscribersNavLink">
            <a class="dropdown-item" href="<%= contacts_url %>">Contacts</a>
            <a class="dropdown-item" href="<%= emaillists_url %>">Email List</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle p-2 text-dark" href="#" id="subscribersNavLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
          <div class="dropdown-menu" aria-labelledby="subscribersNavLink">
            <a class="dropdown-item" href="<%= from_emails_url %>">From Emails</a>
            <a class="dropdown-item" href="<%= user_url(current_user) %>">Account Detail</a>
          </div>
        </li>
<!--        <li class="nav-item"><a class="nav-link p-2 text-dark" href="<%#= user_url(current_user) %>">Account</a></li>-->
        <li class="nav-item"><a class="nav-link p-2 text-dark" href="/logout">Log Out</a></li>
      <% else %>
        <li class="<%= 'current' if current_page?('/') %>"><a href="/" class="nav-link p-2 text-dark"><div>Home</div></a>
        <li class="<%= 'current' if current_page?(action: 'features', controller: 'pages') %>"><a class="nav-link p-2 text-dark" href="/features"><div>Features</div></a>
        <li class="<%= 'current' if current_page?(action: 'pricing', controller: 'pages') %>"><a class="nav-link p-2 text-dark" href="/pricing"><div>Pricing</div></a>
        <li class="<%= 'current' if current_page?('/login') %> nav-item"><a class="nav-link p-2 text-dark" href="/login">Log In</a></li>
      <% end %>
      <%# unless current_page?('/signup') or logged_in? %>
      <% unless logged_in? %>
        <li class="nav-item"><a class="nav-link btn btn-outline-primary ml-2<%= ' btn-dark text-light' if current_page?('/signup') %>" href="/signup">Sign up</a></li>
      <% end %>
    </ul>
  </div>

  <main role="main" class="container">
    <%= yield %>
  </main>

  <footer class="pt-4 mb-0 pb-md-3 mt-5 pt-md-5 border-top bg-white">
    <div class="container">
      <div class="row">
        <div class="col-12 col-md">
          <h2>OwlCampaign</h2>
          <small class="d-block mb-3 text-muted">&copy; <%= Time.zone.now.year %>, All Rights Reserved. </small>
        </div>
        <div class="col-6 col-md">
          <h5>Products</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="/features">Features</a></li>
            <li><a class="text-muted" href="/pricing">Pricing</a></li>
            <li><a class="text-muted" href="/security">Security</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Help</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="/guides">Guides and Tutorials</a></li>
            <li><a class="text-muted" href="/faqs">FAQs</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>About Us</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="/about">About</a></li>
            <li><a class="text-muted" href="/privacy">Privacy</a></li>
            <li><a class="text-muted" href="/terms">Terms</a></li>
            <li><a class="text-muted" href="/contact">Contact</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/layouts/campaign_mailer.html.erb
<%= yield %>